POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Agile Developer",
    "author": "Venkat Subramaniam",
    "url": "http://blog.agiledeveloper.com/",
    "likes": 1
}